### ISSUE TITLE
Export for Overlay-Tool

### ISSUE THREAD

**Issue by jensbuehl** [jensbuehl/aoe4-guides#36]

**Comment by jensbuehl** [comment]
Idea: Use JSON based "graphical" output. Just skip the icons in the build steps for now.
Mapping about like that:

`

    "civilization": "{build.civ}",
    "name": "{build.title}",
    "author": "{build.author}",
    "source": "",
    "build_order": [
        {
            "age": -1,
            "population_count": -1,
            "time": "{step.time}",
            "villager_count": {step.villagers},
            "resources": {
                "food": {step.food},
                "wood": {step.wood},
                "gold": {step.gold},
                "stone": {step.stone}
            },
            "notes": [
                "Plain text here."
            ]
`

**Comment by jensbuehl** [comment]
merged in #41

**Comment by CraftySalamander** [comment]
Very nice work.
Super fast, and seems to work well.

Here are some improvement suggestions:
* For the source, it would be nice to add the page url (e.g. https://aoe4guides.com/builds/DRGeGvP8AncxFxSAayRh), or at least "https://aoe4guides.com" (no impact on the BO, but better for traceability).
* When the time is not indicated (i.e. ""), better to not add the time field to the export (for this particular step), in order to avoid to have an empty time measure.
* When you have a resource (food, wood, stone, gold) set to 0, export it as 0 (and not -1). Resources are always indicated on the AoE4 UI, even when set to 0. It makes it easier to read (but keep "builders" to -1 when not indicated).
* If your website does not support lines return, maybe better to split in sub-notes at the end of each sentence (you can split with ". ". If you can edit the returns, better to keep it as it is.
* [Here](https://github.com/CraftySalamander/buildorderguide/blob/rts_overlay_export/src/Builds/RTSOverlay.js#L557) is an example ("convertTxtToIllustrated" function) to convert text to text mixing images, by analysing patterns, but you will need to adapt [this dictionary](https://github.com/CraftySalamander/buildorderguide/blob/rts_overlay_export/src/Builds/RTSOverlay.js#L8) for AoE2. However, since you have a task to add images (like in age4builder), better to keep it as it is for now.
* "builders" is part of "resources", not next to it.

**Comment by jensbuehl** [comment]
Thanks for the additional information and testing! All valid points!
I'll take a look. Might take a bit longer since the public holidays are history. ;)

**Comment by jensbuehl** [comment]
These were mostly very minor changes, so I did it rightaway. Included a link to your project page as well next to the button.

**Comment by CraftySalamander** [comment]
Great! :-)

**Comment by CraftySalamander** [comment]
Small extra details.
When testing [this BO](https://aoe4guides.com/builds/9Y2B5M2JD57xdOrh0icW).

I get this for the last step:
```
"notes": [
            "When white tower complete, balance based on composition.<br>Follow up ideas:<br>- open with knights + longbows<br>- transition into crossbow + spears<br>- build blacksmith and get upgrades<br>- gather relics<br>"
         ]
```

It would be better to split it like this:
```
"notes": [
            "When white tower complete, balance based on composition.",
            "Follow up ideas:",
            "- open with knights + longbows",
            "- transition into crossbow + spears",
            "- build blacksmith and get upgrades",
            "- gather relics"
         ]
```

However, when testing on RTS Overlay, it displays it correctly (so not a necessary change, only a cleaner one).

On the same BO, I also have this note: `"Age up&nbsp; with white tower with ~10 villagers from sheep"`.
I do not know where the `&nbsp;` is coming from.

Other than that, it looks very nice on the overlay ;-)

**Comment by jensbuehl** [comment]
Splitting the lines is changed on dev branch already.
The redundant "space" was indeed somehow part of the BO. I just removed it there...
