### ISSUE TITLE
Add REST API

### ISSUE THREAD

**Issue by BjornTheProgrammer** [jensbuehl/aoe4-guides#79]
Hello,

I wish to use the build order data from this project to create an aoe4 mod that allows people to practice build orders in a game. However, I am unfortunately not familiar with Firebase. Would you be willing to add a REST API that allows people to get data from the website easily?

Awesome project btw.

**Comment by jensbuehl** [comment]
Hey, neat idea.
Unfortunately, not possible in the short term. No time due to family business. ;)

**Comment by BjornTheProgrammer** [comment]
Would you be fine with me making a pull request adding this functionality?

**Comment by jensbuehl** [comment]
I would be happy to test and review.
Should be pretty easy. (https://blog.logrocket.com/building-rest-api-firebase-cloud-functions-typescript-firestore/)

However, I am a bit hesitant. Since the traffic exploded recently (and also the costs - it's no longer free tier), I am not eager adding more cloud functions that add more on top and open it up to an even broader audience. We could give it a try and check the impact.

**Comment by jensbuehl** [comment]
Hi @BjornTheProgrammer 
I have created a separate repository for the API project: https://github.com/jensbuehl/aoe4-guides-api
Hello world example is [live](https://aoe4-guides-api-qq36r4yzha-ey.a.run.app/status)

Due to busy times I cannot push it in the short term but whenever I find time I might look into it.
TODOs from the top of my head are: design the API, add swagger doc, add firestore access to query BOs, add overlayJson conversion,...

Since I moved the aoe4guides hoster, I could cut the costs which allows for some more experiments on gcloud. ;)

**Comment by jensbuehl** [comment]
v1 published and ready for testing and integration.
https://aoe4guides.com/api/api-docs/

**Comment by BjornTheProgrammer** [comment]
@jensbuehl I'll write an issue on the new repository when I have some time about some proposals for the API. Thank you so much for the project! I wasn't experienced enough with firebase to create a mirrored project to test on to create this.
