### ISSUE TITLE
Link icons to aoe4world explorer 

### ISSUE THREAD

**Issue by schwazza** [jensbuehl/aoe4-guides#90]
Maybe its a lot of work and not worth it...

I like to learn new civs with the help of a build order. For this reason I dont know the exact function for every technology. It would be helpful to click on the icon and get directly to the aoe4world explorer page.

**Comment by jensbuehl** [comment]
Good idea. 

The data that I am using started off with the overlay tool structure and is hand crafted. At some point I wanted to use the aoe4 data project which backs everything on aoe4world. (it's also on github)

However, replacing / transforming all icon descriptors or enriching it is indeed a lot of tedious work.

I thought that having the Information in the popup would be sufficient instead of linking to aoe4world.

So, at some point it might be a thing. But not anytime soon I guess.

**Comment by jensbuehl** [comment]
Implemented in version 1.7.12
Tooltip + Naviagation to aoe4worl explorer on click:
![image](https://github.com/jensbuehl/aoe4-guides/assets/3983913/29a29516-f8b6-4508-ad11-ac02ea9c6c17)
